# Generated by Django 4.0.4 on 2022-08-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp1', '0003_group_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='payhead_crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('payhead_type', models.CharField(max_length=100, null=True)),
                ('income_type', models.CharField(max_length=100, null=True)),
                ('under_name', models.CharField(max_length=100, null=True)),
                ('net_salary', models.CharField(max_length=100, null=True)),
                ('pay_slip_name', models.CharField(max_length=100, null=True)),
                ('currency_ledger', models.CharField(max_length=100, null=True)),
                ('calculation_type', models.CharField(max_length=100, null=True)),
                ('attendance_type', models.CharField(max_length=100, null=True)),
                ('production_type', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
