# Generated by Django 4.0.4 on 2022-09-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp1', '0006_ledger_ledger_tax_register_ledger_tax_ledger_sundry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=225)),
                ('particular', models.CharField(max_length=225)),
                ('voucher_type', models.CharField(max_length=225)),
                ('voucher_number', models.CharField(max_length=225)),
                ('quntity', models.CharField(max_length=225)),
                ('value', models.CharField(max_length=225)),
            ],
        ),
    ]
