# Generated by Django 4.0.4 on 2022-09-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp1', '0008_add_voucher2'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_voucher3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='Null', max_length=225)),
                ('particular', models.CharField(blank=True, default='Null', max_length=225)),
                ('voucher_type', models.CharField(blank=True, default='Null', max_length=225)),
                ('voucher_number', models.CharField(blank=True, default='Null', max_length=225)),
                ('debit', models.CharField(blank=True, default='Null', max_length=225)),
                ('credit', models.CharField(blank=True, default='Null', max_length=225)),
            ],
        ),
    ]
